In [ ]:
class FeautureGenerator():
    pass
    
    def fit(self,X):
        pass

    def transfor(self,Y):
        pass

    def fit_transform(self,X):
        pass

In [1]:
from sklearn.base import BaseEstimator,TransformerMixin

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\sanaik\Music\FSDS Course\ML Projects\machine_learning_project-main\machine_learning_project-main\Housing\artifact\data_ingestion\2022-07-08-11-44-49\ingested_data\train\housing.csv")

In [5]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [6]:
x=df.drop(columns=['median_house_value'],axis=1)
y=df['median_house_value']

In [9]:
for idx,column in enumerate(x.columns):
    print(idx,column)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


In [12]:
x[:,2]

InvalidIndexError: (slice(None, None, None), 2)

In [10]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"
DATASET_SCHEMA_COLUMNS_KEY=  "columns"


In [ ]:
class FeatureGenerator(BaseEstimator, TransformerMixin):

    def __init__(self, add_bedrooms_per_room=True,
                 total_rooms_ix=3,
                 population_ix=5,
                 households_ix=6,
                 total_bedrooms_ix=4, columns=None):
        """
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of  households columns
        total_bedrooms_ix: int index number of bedrooms columns
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
        except Exception as e:
            raise HousingException(e, sys) from e

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / \
                                 X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / \
                                       X[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = X[:, self.total_bedrooms_ix] / \
                                    X[:, self.total_rooms_ix]
                generated_feature = np.c_[
                    X, room_per_household, population_per_household, bedrooms_per_room]
            else:
                generated_feature = np.c_[
                    X, room_per_household, population_per_household]

            return generated_feature
        except Exception as e:
            raise HousingException(e, sys) from e


In [13]:
room_per_household = x[:, 3] / \
                                 x[:, 6]

InvalidIndexError: (slice(None, None, None), 3)

In [14]:
x.iloc[:,3]

0        3873.0
1        5320.0
2        1618.0
3        1877.0
4        3536.0
          ...  
16507    6665.0
16508    7901.0
16509     707.0
16510    3155.0
16511    1079.0
Name: total_rooms, Length: 16512, dtype: float64

In [15]:
import numpy as np

In [21]:
x=np.arange(10)

In [22]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[1:3]

array([1, 2])

In [8]:
import dill
import numpy as np

In [10]:
x=np.array([[12,13,45,50],[2,6,22,25]])

In [11]:
type(x)

numpy.ndarray

In [13]:
x[:,2]

array([45, 22])